input {
  mongodb {
    uri => "${MONGODB_URI}"
    database => "orderdb"
    collection => "support_query_events"
    schedule => "* * * * *"
    full_document => true
    placeholder_db_dir => "/tmp/logstash-mongodb"
    placeholder_db_name => "logstash_mongodb_plugin"
  }
}

filter {
  mutate {
    rename => { "_id" => "mongo_id" }
    remove_field => ["@version"]
  }

  date {
    match => ["createdAt", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOSTS}"]
    user => "${ELASTICSEARCH_USERNAME}"
    password => "${ELASTICSEARCH_PASSWORD}"
    ssl_enabled => true
    ilm_enabled => false
    index => "support-query-events-%{+YYYY.MM.dd}"
    retry_on_conflict => 3
  }

  stdout { codec => rubydebug }
}
